accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unlicense",
    "BSL-1.0",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "Zlib",
    "ISC",
    "CC0-1.0",
    "MPL-2.0",
    "bzip2-1.0.6",
    "NCSA"
]
